# Generated by Django 4.1.3 on 2022-11-18 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ShortMessage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("message", models.TextField()),
                ("response_message", models.TextField()),
                (
                    "status_code",
                    models.CharField(
                        choices=[
                            ("100", "Processed"),
                            ("101", "Sent"),
                            ("102", "Queued"),
                            ("401", "Risk Hold"),
                            ("402", "Invalid SenderId"),
                            ("403", "Invalid Phone Number"),
                            ("404", "Unsupported Number Type"),
                            ("405", "Insufficient Balance"),
                            ("406", "User In Blacklist"),
                            ("407", "Could Not Route"),
                            ("500", "Internal Server Error"),
                            ("501", "Gateway Error"),
                            ("502", "Rejected By Gateway"),
                        ],
                        max_length=60,
                    ),
                ),
                ("phone_number", models.CharField(max_length=50)),
                ("cost", models.CharField(max_length=50)),
                ("status", models.CharField(max_length=50)),
                ("message_id", models.CharField(max_length=100)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
