SMS_STATUS_CODE_CHOICES = (
    ("100", "Processed"),
    ("101", "Sent"),
    ("102", "Queued"),
    ("401", "Risk Hold"),
    ("402", "Invalid SenderId"),
    ("403", "Invalid Phone Number"),
    ("404", "Unsupported Number Type"),
    ("405", "Insufficient Balance"),
    ("406", "User In Blacklist"),
    ("407", "Could Not Route"),
    ("500", "Internal Server Error"),
    ("501", "Gateway Error"),
    ("502", "Rejected By Gateway"),
)
